services:
  postgres:
    image: postgres:16.3
    restart: always
    container_name: web4-postgres
    ports:
      - "127.0.0.1::5432"
    volumes:
      - web4_postgres_data:/var/lib/postgresql/data
      - ${CONFIG_BASE_PATH}/service/postgres/init:/docker-entrypoint-initdb.d
    env_file:
      - ${CONFIG_BASE_PATH}/service/postgres/secret/postgres-secret.env
      - ${CONFIG_BASE_PATH}/service/postgres/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - web4_postgres_network

volumes:
  web4_postgres_data:

networks:
  web4_postgres_network:
    external: true
